### ISSUE TITLE
Daily issue data

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_shri#26]
Daily issue

1. To add submission Time (or date-time)
2. Submissions by users that don’t have a match in the facility-userid document should be dropped during data cleaning (for example Hpitchik user)
3. “Submitted by” doesn’t need to be included in cleaned data as it corresponds directly with the facility

**Comment by siddhant3030** [comment]
- Time with separate column for daily_issue_clean table. 
 - daily_issue_clean doesn't need submitted_by column

**Comment by helenpitchik** [comment]
I'm not seeing these two changes in the data yet!

In addition: 

* replace the text in the "issue" column with the free text that was entered in the "other_other_fixed" cell
* the issue category "Supplies - harpic" should be replaced with "Supplies - harpic etc"
* the issue category "Technology - Internet" should be replaced with "Technology - internet"

**Comment by siddhant3030** [comment]
- Others issue should be move to issue column

**Comment by siddhant3030** [comment]
I have fixed other two issue which has name changes

**Comment by helenpitchik** [comment]
A couple of fixes on this: 
1. As discussed can you make the two variables "category" and "issue"? 
2. Can you change the response in the shutdown column to be in lower case (yes and no, instead of YES and NO)?

**Comment by siddhant3030** [comment]
@helenpitchik this is done.

**Comment by helenpitchik** [comment]
@siddhant3030 

1. Submissions by users that don’t have a match in the facility-userid document should be dropped during data cleaning (for example Hpitchik user)

2. _submission_time is in UTC. Can we use timestampformatted as the date/time variable instead? 

3. I don't see the change where there are meant to be two variables "category" and "issue" yet. Has this been made?

**Comment by siddhant3030** [comment]
> * _submission_time is in UTC. Can we use timestampformatted as the date/time variable instead?
> *

Date_auto and time_auto should be from timestamp_formatted

**Comment by helenpitchik** [comment]
@siddhant3030 

I just took a look at this and have a few questions / comments:

1.  If something is missing can it be included as blank instead of "NA"?
2. Can you include the times in 24 hour clock time? 
3. When multiple categories are selected but then only some report issues, for the ones where no issues is reported your code is producing an additional row with no issue reported. For example for _id=218704844, there should only be only row of output produced indicating that there was a Toilet tap issue in the cateogry of "Plumbing" at that time. Currently you are also producing an additional row reporting no issue. 
4. Is the variable "shutdown" being manipulated from the raw data? 
5. Does the issue with production mean that I am unable to download the data through R? I have been unable to get data with the "category" column included and wondering if the issue is from my end or due to the issue you mentioned? 

Once these are updated I will check again! 
Helen

**Comment by siddhant3030** [comment]
@helenpitchik
1. For the first one it can be null 
2. Can you give an example? What do you want to expect? 
3. As far as I see I can only see one data which for which issue is being reported. are you seeing two id's which is same? 
4. The way we have written the logic is  
```

electrical_group_outage_bulb_hours, 
                    electrical_group_outage_wiring_hours,
                    electrical_group_outage_boring_hours,
                    plumbing_group_outage_basintap_hours, 
                    plumbing_group_outage_toilettap_hours, 
                    plumbing_group_outage_pipe_hours,
                    technology_group_outage_internet_hours, 
                    technology_group_outage_tablet_hours,
                    supplies_group_outage_harpicetc_hours,
                    supplies_group_outage_soap_hours,
                    infrastructure_group_outage_gate_hours
```
We check all these variables and if it has 0 then 'no' and if has 1 then 'yes'
5. No you still can. Will explain you more about this when you start using our product

**Comment by helenpitchik** [comment]
2. 24 hour clock, where 5pm = 17:00, 6pm = 18:00 etc. 
3. Additional ID with this issue: 221162480
4. There is another variable which indicates if thee was a shutdown or not, which is the _out_ variable 

6. Another point: Some IDs are not appearing in the using data, for example 233336867, 225174919, 233524167

**Comment by helenpitchik** [comment]
Plumbing - basin tap
Plumbing - pipe
Plumbing - socket
Plumbing - tools
Plumbing - toilet tap

Electrical - bulb
Electrical - wiring
Electrical - switch
Electrical - stabilizer
Electrical - boring

Infrastructure - painting
Infrastructure - floor
Infrastructure - wall
Infrastructure - gate
Infrastructure - roof
Infrastructure - roof
Infrastructure - pan

Cleanliness - pan
Cleanliness - odor
Cleanliness - wall
Cleanliness - basin
Cleanliness - drain blocked

Supplies - soap
Supplies - harpic etc
Supplies - jug
Supplies - dustbin
Supplies - gloves

Technology - tablet
Technology - internet

**Comment by siddhant3030** [comment]
@helenpitchik I have fixed the date and included all this in issues. 

can you send me the R logic of just the daily_issue_clean table
