### ISSUE TITLE
Enrollment data

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_shri#27]
1. In enrollment the numbers are lower in your file than they are in the one I have (2794 compared to 2802)
2. I went back and pulled the raw data and yours has 1 less than mine (2866 compared to 2867). So most of the differences must come from the cleaning process
3. Can you share how you get from 2866 to 2794? (with some comments on it so I can try to follow)?

**Comment by siddhant3030** [comment]
Duplicates needs to be changed.

**Comment by helenpitchik** [comment]
The total number is the same now, but we are selecting different instances when there are duplicates. Can you switch your code to selecting the most recently entered data when there are duplicates?

**Comment by siddhant3030** [comment]
@helenpitchik is this coming randomly for now
?

**Comment by siddhant3030** [comment]
@helenpitchik this is also done. We will push everything today so that you can test it.

**Comment by helenpitchik** [comment]
I noticed that some of the enrollment dates were the same (so for 2 IDs with duplicates we were selecting different observations). Can you change so duplicates are deleted based on the _submission_time variable (instead of enrollment date)? After this I'll cross-check 1 more time, but it should match!

**Comment by siddhant3030** [comment]
okay I have used _submission_time instead of enrollment date. can you give me those two id's which you were referring to?

**Comment by siddhant3030** [comment]
I'll use date and time to fix it.

**Comment by helenpitchik** [comment]
I have just checked once more -- there are 2 observations with no date_enrollment in your data (not present in mine) I am not sure how they are being included but they should be deleted.

**Comment by siddhant3030** [comment]
hey, can you check again I don't see this?

**Comment by helenpitchik** [comment]
Hi Siddhant, 

These two observations are still there, one has userid "G43" and the other has all their data under a variable called "v1" (not sure what this is), and it says ","gomiasite","Gomia",2022-02-11,61,"61-71"

Helen

**Comment by siddhant3030** [comment]
@helenpitchik From when exactly do you want us to pull the data? I think this is some old data which is in raw

**Comment by helenpitchik** [comment]
Maybe I am misunderstanding how the process is meant to work! How come there is old data in raw within the formatted data sheet?

**Comment by siddhant3030** [comment]
@helenpitchik let's discuss this tomorrow.

**Comment by siddhant3030** [comment]
@helenpitchik please look the csv readings

**Comment by helenpitchik** [comment]
Can you refresh this fully? I updated the data and want to look again. I think it might have fixed the issue, but want to check
